### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by jt14den** [ucla-data-science-center/twitter-scraper#6]

**Comment by lawtlee** [comment]
Is there a license that I should use?

**Comment by jt14den** [comment]
lm look it up



On March 7, 2024 at 4:43:04 PM, Lawrence Lee ***@***.******@***.***>) wrote:

Is there a license that I should use?

**Comment by jt14den** [comment]
BSD is what we should use per the TDL @lawtlee https://opensource.org/license/bsd-3-clause

**Comment by jt14den** [comment]
Sorry, TDL is the https://tdg.ucla.edu/about/faq/open-source-other-software-sharing-options - technology transfer on campus
